### PR TITLE
Jest 27 support

### LINKED ISSUE #26: Doesn't work with Jest 27
Looks like Jest 27 introduced a breaking change to `jest-mock` -- it no longer exports a global instance of `ModuleMocker`: facebook/jest#10887

I think fixing jest-create-mock-instance to work with both Jest <27 and 27+ should be reasonably simple, so I'll submit a PR if that's okay 😃

### PR DESCRIPTION
**Pull request by gustavohenke**
Fixes #26.

Took the freedom to upgrade jest in the dependencies too. Should still work for Jest 26-!

### CODE REVIEW

**Comment by gustavohenke** [comment]
ping @asvetliakov

**Comment by korzo** [comment]
@gustavohenke  As this project seems no longer supported, would you mind to publish your fork to npm?

**Comment by darraghoriordan** [comment]
I forked this fix and published here in case anyone needs it: https://www.npmjs.com/package/@darraghor/jest-create-mock-instance

I'd recommend keeping an eye on this PR and changing back to this main version if this does get merged though

thanks for the fix gustavohenke!

**Comment by asvetliakov** [comment]
Thank you for the PR!

**Pull request merged**
